# Generated by Django 4.1.2 on 2022-10-23 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='parent_name',
            new_name='s_parent_name',
        ),
    ]
