# Generated by Django 4.1.2 on 2022-11-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=30)),
                ('s_email', models.CharField(max_length=30)),
                ('s_dob', models.CharField(max_length=20)),
                ('s_phone_number', models.BigIntegerField()),
                ('s_place', models.CharField(max_length=30)),
                ('parent_name', models.CharField(max_length=30)),
                ('s_password', models.CharField(max_length=20)),
            ],
        ),
    ]
