# Generated by Django 4.1.2 on 2022-11-03 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student1',
            old_name='s_dob',
            new_name='student_dob',
        ),
        migrations.RenameField(
            model_name='student1',
            old_name='s_email',
            new_name='student_email',
        ),
        migrations.RenameField(
            model_name='student1',
            old_name='s_name',
            new_name='student_name',
        ),
        migrations.RenameField(
            model_name='student1',
            old_name='s_password',
            new_name='student_password',
        ),
        migrations.RenameField(
            model_name='student1',
            old_name='s_phone_number',
            new_name='student_phone_number',
        ),
        migrations.RenameField(
            model_name='student1',
            old_name='s_place',
            new_name='student_place',
        ),
    ]
